language: node_js
node_js:
- '8.10.0'

branches:
  only:
  - source

install: npm install

before_script:
- git config --global user.email sendzation@gmail.com
- git config --global user.name "sendz"
- git remote set-url origin https://${GITHUB_TOKEN}@github.com/kdeid/kdeid.github.io.git
- sed -i "s/__GITHUB_TOKEN__/${GITHUB_TOKEN}/" _config.yml

script: npm run build
